# Bestandsnaam: .github/workflows/dotnet-ci.yml

name: .NET CI Build, Test, Analyze (SonarCloud met Cobertura)

on:
  push:
    branches: [ main ] # Of 'master' als dat je branch is
  pull_request:
    branches: [ main ] 

jobs:
  build-test-analyze:
    name: Build, Test & Analyze
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    steps:
    # Stap 1: Code ophalen
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 

    # Stap 2: .NET SDK installeren
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    # Stap 3: Cache (optioneel)
    - name: Cache NuGet packages
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    # Stap 4: Dependencies herstellen
    - name: Restore dependencies
      run: dotnet restore

    # Stap 5: SonarScanner installeren
    - name: Install SonarScanner
      run: dotnet tool install --global dotnet-sonarscanner

    # Stap 6: SonarScanner 'begin' stap (AANGEPAST)
    - name: SonarScanner Begin Analysis
      run: |
        dotnet sonarscanner begin \
          /o:"daviddierckx-1" \
          /k:"daviddierckx_AvansDevOpsProject" \
          /d:sonar.host.url="https://sonarcloud.io" \
          /d:sonar.login="${{ env.SONAR_TOKEN }}" \
          /d:sonar.cs.cobertura.reportsPaths="./TestResults/coverage.cobertura.xml"  # <-- BELANGRIJKE WIJZIGING

    # Stap 7: Code bouwen
    - name: Build project
      run: dotnet build --configuration Release --no-restore

    # Stap 8: Unit Tests uitvoeren (AANGEPAST)
    - name: Run tests with Cobertura coverage
      run: |
        dotnet test \
          --configuration Release \
          --no-build \
          --collect:"XPlat Code Coverage" \
          --results-directory ./TestResults # <-- BELANGRIJKE WIJZIGING

    # Stap 9: SonarScanner 'end' stap
    - name: SonarScanner End Analysis
      run: dotnet sonarscanner end /d:sonar.login="${{ env.SONAR_TOKEN }}"
